/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import aoc.day01.Day01
import java.io.File
import java.nio.charset.StandardCharsets

class App {
    private val days: Map<Int, Day> = mapOf(
            1 to Day01()
    )

    private fun loadInput(day: Int): String {
        val paddedDay: String = day.toString().padStart(2, '0')
        val fileName = "day$paddedDay.txt"
        var result = ""
        ClassLoader.getSystemResourceAsStream(fileName).bufferedReader().use {
            result = it.readLine()
        }
        return result
    }

    fun exec(day: Int): String? {
        val input = loadInput(day)
        return days[day]?.exec(input)
    }

}
fun main(args: Array<String>) {
    val day = if (args.isEmpty()) 1 else args[0].toInt()
    println(App().exec(day))
}
